
dist: trusty

language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

services: docker

matrix:
  include:
      # linux
      - os: linux   # abi 57
        env: CXX="g++-7"
      # os x x86
      - os: osx     # abi 64
        env: CXX="clang"

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run -v `pwd`:/build --rm spacedragon/centos6_builder:v2 /bin/bash -c 'source scl_source enable devtoolset-3 && cd /build && source ~/.bashrc && export CC=gcc && export CXX=g++ && yum install -y autoconf automake && ./autogen.sh && ./configure --disable-yaml --disable-xml && make -j4';
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      ./autogen.sh;
      ./configure --disable-yaml --disable-xml;
      make -j4;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      mv ctags ctags-linux;
      ./ctags-linux --version;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mv ctags ctags-darwin;
      ./ctags-darwin --version;
    fi

git:
  depth: 10

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(?:-[a-z0-9.-]+)?$/


deploy:
  provider: releases
  api_key:
    secure: V/dUyqOPRTPknYxAqB/87NtFRSUCKdoMoMwspxK3hwHEPMKvO0DzXtobMBAl7RJQS7vwnbOktbLQ7hKovKdkFG97wDuwuG/cJTDr241ULWGM3uyfTs8T+2LZYVrIhVAHrQZQCIgXWc6bgqyVRtwVnvr80W9VzKu0E/05fa14LlY+bAe2Dy5uk8d3UcFtRCRZTUFMY8WUQFPStS0aWyywl77wXEavSlFY602mMRIbbFNTwFpSzLumYoxxzeogb2Iy1frENo3113kQARGeRnhljqh8+Jl8en2cFvWAAVWFlouBhfHhyYLFp78a+3pMAJtKbAOeMAVn/ixtLyUHsDhIGcZOzWWUn8EJ2AmUM22U/8qGlYaxW9DH2+ydg5fu/Hf2zPoN9ophp7J+WNU1i9vqdR3KK2Ds2lKuGGXEkg0o21+tDk989nht7r/pdhU4j4mHC/5/goi0Orc50IO2v/xMBx0va0HW+uewPNiDPvkCffMT2nUwIFisXZQCcjEPExhRjdygCKliUl0jAhY2prJpsNGjsUIMchAd8V8iXjfd5E8U8ppTMjiTBzMH0jaewkJIjK/DcFKcVBUvoW0UhzPJtq42hGYRIiuJwvoPF5aatcJRCcSPtlyJhGavc759SnYyJFsax+fz2d0BeLDD2fDMShDqyek72knbYHP2oVUFNk0=
  skip_cleanup: true
  file_glob: true
  file: "ctags-*"
  overwrite: true
  on:
    repo: elastic/ctags
    tags: true
