version: 1.0.{build}

environment:
  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64

matrix:
  fast_finish: true

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\win32\appveyor.bat build'

# after_build:
#   - '%APPVEYOR_BUILD_FOLDER%\win32\appveyor.bat package'

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\win32\appveyor.bat test'
  - mv ctags.exe ctags-win32.exe

artifacts:
  - path: ctags-win32.exe

deploy:
  - provider: GitHub
    description: |
      Universal Ctags pre builds used by ([@elastic/ctags-langserver](https://github.com/elastic/ctags-langserver)).
    auth_token:
      secure: AfJEZz4Zv9OTyO2KxHZ3nF6JSFu0gjfKJKxS/WIyb3wInsmCAeBKlzunN5F1q7DU
    artifact: ctags-win32.exe
    prerelease: true
    on:
      appveyor_repo_tag: true
